# EzSpawn by team Devity

location:
  world: world
  # ------------------------------------------------------------------------------------
  # Don't change these
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  # ------------------------------------------------------------------------------------

spawn:
  # Main plugin prefix
  prefix: "&f[&6EzSpawn&f]"

   # On /spawn
   # Clear INV on /spawn & Join
  clearInventory: true

  # Clear Potion Effects on /spawn & Join
  clearPotionEffects: true

  # Heal players on /spawn
  heal: true 

  # Always teleport to spawn 
  teleportOnJoin : true

  # Make the player respawn at bed location
  # I am still testing this feature (Use on  your own risk)
  respawnAtBed: false

  # Custom message to be sent on /spawn
  message: "&aTeleported to spawn"

  # Custom sound effent on /spawn
  soundEffect: ENTITY_PLAYER_LEVELUP
