# EzSpawn by team Devity

spawn:
  world: world
  # ------------------------------------------------------------------------------------
  # Don't change these
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  # ------------------------------------------------------------------------------------

  # On /spawn
   # Clear INV on /spawn & Join
  clearInventory: true

  # Clear Potion Effects on /spawn & Join
  clearPotionEffects: true

  # Heal players on /spawn
  heal: true 

  # Always teleport to spawn 
  teleportOnJoin : true

  # Custom message to be sent on /spawn
  message: "&aYou have been teleported to spawn."

